version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: symfony_dev:latest
    container_name: symfony_crypto_app
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"
      VAULT_DEK_KEY: "symfony-dek-key"
      VAULT_SIGN_KEY: "symfony-sign-key"
      VAULT_KV_PATH: "secret/data/symfony-crypto-salt"
    volumes:
      - ./symfony/:/var/www/symfony
    working_dir: /var/www/symfony

  nginx:
    image: nginx:stable
    container_name: symfony_crypto_nginx
    ports:
      - "2443:443"
    volumes:
      - ./symfony/:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php

  vault:
    image: hashicorp/vault:1.14.2
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8205:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    volumes:
      - ./docker/vault/entrypoint.sh:/vault/entrypoint.sh
    entrypoint: ["/vault/entrypoint.sh"]