# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    vault.url: '%env(resolve:VAULT_ADDR)%'
    vault.token: '%env(resolve:VAULT_TOKEN)%'
    vault.dek_key: '%env(resolve:VAULT_DEK_KEY)%'
    vault.sign_key: '%env(resolve:VAULT_SIGN_KEY)%'
    vault.kv_path: '%env(resolve:VAULT_KV_PATH)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\VaultService:
        arguments:
            $vaultUrl: '%vault.url%'
            $vaultToken: '%vault.token%'
            $dekKeyName: '%vault.dek_key%'
            $signKeyName: '%vault.sign_key%'
            $kvPath: '%vault.kv_path%'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
